services:
  - type: web
    name: django-mini-blog
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn blog.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: django-mini-blog.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: django-mini-blog-db
          property: connectionString

databases:
  - name: django-mini-blog-db
    databaseName: django_mini_blog
    user: django_mini_blog_user
    plan: free 